### ISSUE TITLE
когда ia3ps

### ISSUE THREAD

**Issue by GDenisC** [mat1rus/ia2ps#1]

**Comment by matt7ress** [comment]
а за взлом бан вщает

**Comment by matt7ress** [comment]
а реаерс енжинер это вроде взлмо все не будет

**Comment by GDenisC** [comment]
https://cdn.discordapp.com/attachments/1121128549760372777/1280488769857785907/IMG_2615.jpg?ex=66d84399&is=66d6f219&hm=ad1f32bb1c364bb8394d060c5654c13f373126af1487c3222dc811d9470bd9ad&

**Comment by GDenisC** [comment]
а вы знали что IA3 после kafif backrooms update и 1000 часов после

**Comment by GDenisC** [comment]
и про взлом ничего не написано!!!!!!!!!!!!!!!!!111
